<a href="https://colab.research.google.com/github/Quantzaar/Strategy/blob/main/bactest%20results/Backtest_nifty50_momentum_strategy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#To upload file from local drive

#from google.colab import files

#uploaded = files.upload()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
ls

drive/  sample_data/

In [ ]:
import os
cwd = os.getcwd()
print(cwd)

/content

In [ ]:
import pandas as pd

filepath = r"/content/drive/MyDrive/Quantzaar-tradingS, InvestmentS, Trade&investMyTheory/Backtesting/ind_nifty200list.csv"

df=pd.read_csv(filepath)

In [ ]:
df.head()

,Company Name,Industry,Symbol,Series,ISIN Code
0,ABB India Ltd.,Capital Goods,ABB,EQ,INE117A01022
1,ACC Ltd.,Construction Materials,ACC,EQ,INE012A01025
2,APL Apollo Tubes Ltd.,Capital Goods,APLAPOLLO,EQ,INE702C01027
3,AU Small Finance Bank Ltd.,Financial Services,AUBANK,EQ,INE949L01017
4,Adani Energy Solutions Ltd.,Power,ADANIENSOL,EQ,INE931S01010

In [ ]:
import yfinance as yf
import numpy as np
import pandas as pd

stocks = pd.read_html('https://en.wikipedia.org/wiki/NIFTY_50')

In [ ]:
stocks[2]

,Company name,Symbol,Sector[14],Date added[15]
0,Adani Enterprises,ADANIENT,Diversified,30 September 2022
1,Adani Ports & SEZ,ADANIPORTS,Infrastructure,28 September 2015
2,Apollo Hospitals,APOLLOHOSP,Healthcare,31 March 2022
3,Asian Paints,ASIANPAINT,Consumer Durables,27 April 2012
4,Axis Bank,AXISBANK,Banking,27 March 2009
5,Bajaj Auto,BAJAJ-AUTO,Automotive,1 October 2010
6,Bajaj Finance,BAJFINANCE,Financial Services,29 September 2017
7,Bajaj Finserv,BAJAJFINSV,Financial Services,2 April 2018
8,Bharat Petroleum,BPCL,Energy - Oil & Gas,28 October 2002
9,Bharti Airtel,BHARTIARTL,Telecommunication,1 March 2004
10,Britannia Industries,BRITANNIA,Consumer Goods,29 March 2019
11,Cipla,CIPLA,Pharmaceuticals,7 October 1998
12,Coal India,COALINDIA,Energy - Coal,10 October 2011
13,Divi's Laboratories,DIVISLAB,Pharmaceuticals,25 September 2020
14,Dr. Reddy's Laboratories,DRREDDY,Pharmaceuticals,1 October 2010
15,Eicher Motors,EICHERMOT,Automotive,1 April 2016
16,Grasim Industries,GRASIM,Materials,2 April 2018
17,HCLTech,HCLTECH,Information Technology,28 October 2002
18,HDFC Bank,HDFCBANK,Banking,22 April 1996
19,HDFC Life,HDFCLIFE,Financial Services,31 July 2020
20,Hero MotoCorp,HEROMOTOCO,Automotive,7 October 1998
21,Hindalco Industries,HINDALCO,Metals,22 April 1996
22,Hindustan Unilever,HINDUNILVR,Consumer Goods,22 April 1996
23,ICICI Bank,ICICIBANK,Banking,25 January 2002
24,IndusInd Bank,INDUSINDBK,Banking,1 April 2013
25,Infosys,INFY,Information Technology,7 October 1998
26,ITC,ITC,Consumer Goods,22 April 1996
27,JSW Steel,JSWSTEEL,Metals,28 September 2018
28,Kotak Mahindra Bank,KOTAKBANK,Banking,8 April 2010
29,Larsen & Toubro,LT,Construction,10 December 2004
30,LTIMindtree,LTIM,Information Technology,13 July 2023
31,Mahindra & Mahindra,M&M,Automotive,18 September 1996
32,Maruti Suzuki,MARUTI,Automotive,1 March 2004
33,Nestlé India,NESTLEIND,Consumer Goods,27 September 2019
34,NTPC,NTPC,Energy - Power,24 September 2007
35,Oil and Natural Gas Corporation,ONGC,Energy - Oil & Gas,12 April 2004
36,Power Grid,POWERGRID,Energy - Power,14 March 2008
37,Reliance Industries,RELIANCE,Diversified,22 April 1996
38,SBI Life Insurance Company,SBILIFE,Financial Services,25 September 2020
39,Shriram Finance,SHRIRAMFIN,Financial Services,28 March 2024
40,State Bank of India,SBIN,Banking,22 April 1996
41,Sun Pharma,SUNPHARMA,Pharmaceuticals,17 January 2002
42,Tata Motors,TATAMOTORS,Automotive,22 April 1996
43,Tata Steel,TATASTEEL,Metals,22 April 1996
44,Tata Consultancy Services,TCS,Information Technology,25 February 2005
45,Tata Consumer Products,TATACONSUM,Consumer Goods,31 March 2021
46,Tech Mahindra,TECHM,Information Technology,28 March 2014
47,Titan Company,TITAN,Consumer Durables,2 April 2018
48,UltraTech Cement,ULTRACEMCO,Materials,28 September 2012
49,Wipro,WIPRO,Information Technology,27 September 2013

In [ ]:
stocks = stocks[2].Symbol
stocks

0       ADANIENT
1     ADANIPORTS
2     APOLLOHOSP
3     ASIANPAINT
4       AXISBANK
5     BAJAJ-AUTO
6     BAJFINANCE
7     BAJAJFINSV
8           BPCL
9     BHARTIARTL
10     BRITANNIA
11         CIPLA
12     COALINDIA
13      DIVISLAB
14       DRREDDY
15     EICHERMOT
16        GRASIM
17       HCLTECH
18      HDFCBANK
19      HDFCLIFE
20    HEROMOTOCO
21      HINDALCO
22    HINDUNILVR
23     ICICIBANK
24    INDUSINDBK
25          INFY
26           ITC
27      JSWSTEEL
28     KOTAKBANK
29            LT
30          LTIM
31           M&M
32        MARUTI
33     NESTLEIND
34          NTPC
35          ONGC
36     POWERGRID
37      RELIANCE
38       SBILIFE
39    SHRIRAMFIN
40          SBIN
41     SUNPHARMA
42    TATAMOTORS
43     TATASTEEL
44           TCS
45    TATACONSUM
46         TECHM
47         TITAN
48    ULTRACEMCO
49         WIPRO
Name: Symbol, dtype: object

In [ ]:
stocks = stocks + '.NS'
stocks.head()

0      ADANIENT.NS
1    ADANIPORTS.NS
2    APOLLOHOSP.NS
3    ASIANPAINT.NS
4      AXISBANK.NS
Name: Symbol, dtype: object

In [ ]:
df = yf.download(stocks.to_list(), start = '2014-01-01')
df.head()

[*********************100%%**********************]  50 of 50 completed

Price        Adj Close                                                        \
Ticker     ADANIENT.NS ADANIPORTS.NS APOLLOHOSP.NS ASIANPAINT.NS AXISBANK.NS
Date
2014-01-01   37.967472    148.394272    932.331421    464.536194  248.000107
2014-01-02   36.074402    144.928909    895.059326    451.336761  244.180847
2014-01-03   35.085476    142.317993    915.643066    455.008545  241.992935
2014-01-06   35.608196    143.219940    909.631531    456.077484  241.110123
2014-01-07   34.181324    138.567795    896.550171    455.426788  236.878265

Price                                                                          \
Ticker     BAJAJ-AUTO.NS BAJAJFINSV.NS BAJFINANCE.NS BHARTIARTL.NS    BPCL.NS
Date
2014-01-01   1459.791260     75.509598    152.003906    288.068878  69.372292
2014-01-02   1446.581909     72.355499    151.897400    280.350159  67.435356
2014-01-03   1443.156006     72.449883    150.571304    280.904541  65.418938
2014-01-06   1437.636230     72.688301    150.179260    280.904541  65.518288
2014-01-07   1438.892456     72.623726    150.430939    282.908905  64.276634

Price       ...        Volume                                           \
Ticker      ... SHRIRAMFIN.NS SUNPHARMA.NS TATACONSUM.NS TATAMOTORS.NS
Date        ...
2014-01-01  ...       52540.0       425464       1958707       1364747
2014-01-02  ...      104861.0      1311399       2116255       3015089
2014-01-03  ...      166850.0      1443488       1816178       5004049
2014-01-06  ...      223531.0      1832494       1538685       5490077
2014-01-07  ...      322912.0      2986634       1244854       4020899

Price
Ticker     TATASTEEL.NS   TCS.NS TECHM.NS TITAN.NS ULTRACEMCO.NS WIPRO.NS
Date
2014-01-01     12526105   529952   698232   538938         51796  1181351
2014-01-02     41987111  1726948  1395500  1570396         81220  2441295
2014-01-03     33417104  2618174  1327296   818984         78848  2953767
2014-01-06     28387844  2311810  1485056   497192         65748  4948206
2014-01-07     40939015  2897486  1914320   713955         98004  3286111

[5 rows x 300 columns]

In [ ]:
df_close = df['Close']
df_close.head()

Ticker,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BHARTIARTL.NS,BPCL.NS,...,SHRIRAMFIN.NS,SUNPHARMA.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,ULTRACEMCO.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2014-01-01,41.192673,156.300003,969.299988,499.750000,258.440002,1917.400024,76.010002,157.029999,304.399628,116.400002,...,654.960144,572.349976,160.500000,370.970978,40.577053,1076.650024,457.024994,230.800003,1769.250000,207.262558
2014-01-02,39.138786,152.649994,930.549988,485.549988,254.460007,1900.050049,72.834999,156.919998,296.243256,113.150002,...,641.855103,573.849976,154.949997,368.398560,39.938721,1083.500000,454.024994,226.350006,1731.099976,207.356308
2014-01-03,38.065861,149.899994,951.950012,489.500000,252.179993,1895.550049,72.930000,155.550003,296.829071,109.766663,...,657.152405,579.700012,156.350006,358.850952,39.300385,1111.099976,458.875000,227.399994,1727.199951,208.725052
2014-01-06,38.632977,150.850006,945.700012,490.649994,251.259995,1888.300049,73.169998,155.145004,296.829071,109.933334,...,640.685852,588.250000,156.800003,363.055847,38.900238,1119.800049,453.962494,227.800003,1724.300049,209.250046
2014-01-07,37.084900,145.949997,932.099976,489.950012,246.850006,1889.949951,73.105003,155.404999,298.947021,107.849998,...,618.373169,594.200012,156.500000,361.225494,37.604515,1103.074951,451.012512,226.050003,1690.199951,206.325058

In [ ]:
df_dret = df_close.pct_change()
df_dret.head()

Ticker,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BHARTIARTL.NS,BPCL.NS,...,SHRIRAMFIN.NS,SUNPHARMA.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,ULTRACEMCO.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2014-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-01-02,-0.049860,-0.023353,-0.039977,-0.028414,-0.015400,-0.009049,-0.041771,-0.000701,-0.026795,-0.027921,...,-0.020009,0.002621,-0.034579,-0.006934,-0.015731,0.006362,-0.006564,-0.019281,-0.021563,0.000452
2014-01-03,-0.027413,-0.018015,0.022997,0.008135,-0.008960,-0.002368,0.001304,-0.008731,0.001977,-0.029901,...,0.023833,0.010194,0.009035,-0.025917,-0.015983,0.025473,0.010682,0.004639,-0.002253,0.006601
2014-01-06,0.014898,0.006338,-0.006565,0.002349,-0.003648,-0.003825,0.003291,-0.002604,0.000000,0.001518,...,-0.025057,0.014749,0.002878,0.011718,-0.010182,0.007830,-0.010706,0.001759,-0.001679,0.002515
2014-01-07,-0.040071,-0.032483,-0.014381,-0.001427,-0.017551,0.000874,-0.000888,0.001676,0.007135,-0.018951,...,-0.034826,0.010115,-0.001913,-0.005042,-0.033309,-0.014936,-0.006498,-0.007682,-0.019776,-0.013978

In [ ]:
df_mret = (df_dret +1).resample('M').prod()
df_mret

Ticker,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BHARTIARTL.NS,BPCL.NS,...,SHRIRAMFIN.NS,SUNPHARMA.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,ULTRACEMCO.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2014-01-31,0.888744,0.940179,0.959662,0.943872,0.869022,0.991708,0.894816,0.975069,0.932642,1.038660,...,0.930080,1.028567,0.878505,0.932258,0.835994,1.040751,0.977490,0.959922,0.966907,1.040438
2014-02-28,1.064476,1.138142,0.989357,1.002756,1.128323,1.023587,1.061678,1.026353,0.913016,1.042184,...,0.945697,1.095125,0.990780,1.192819,0.965595,1.015484,1.044937,1.094561,1.075115,1.038605
2014-03-31,1.447394,1.120777,0.995817,1.158457,1.152677,1.070517,1.091331,1.139676,1.104833,1.217064,...,1.298097,0.891500,1.074087,0.956110,1.145870,0.937339,0.961494,1.083299,1.189077,0.909502
2014-04-30,1.135462,1.004001,0.975885,0.921891,1.038822,0.917715,1.055961,1.044054,1.032415,0.988806,...,0.957394,1.101000,0.996001,1.040386,1.017007,1.026276,1.020497,0.970118,0.926930,0.961616
2014-05-31,1.146105,1.208820,1.014927,1.004850,1.210223,1.016630,1.023854,1.080726,1.048925,1.147285,...,1.289058,0.964997,0.997658,1.000723,1.185823,0.978143,1.049587,1.216402,1.175147,0.969082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-31,1.102862,1.178943,1.113752,0.869342,0.968656,1.128037,0.965298,0.936563,1.134179,1.114723,...,1.201383,1.126246,1.028708,1.133662,0.973854,1.005945,1.047931,1.006013,0.968038,1.014534
2024-02-29,1.045640,1.093446,0.960436,0.954037,1.006884,1.031536,0.979414,0.946444,0.959554,1.202050,...,0.988568,1.112447,1.064445,1.074644,1.036043,1.073154,0.955161,0.980217,0.972958,1.084597
2024-03-31,0.973124,1.016168,1.041825,1.008806,0.974049,1.156625,1.031403,1.115452,1.093693,0.997599,...,0.967686,1.026997,0.921138,1.044833,1.106496,0.946570,0.979786,1.048946,0.985519,0.925762
2024-04-30,0.955460,0.987368,0.935549,1.010240,1.113350,0.973273,0.982450,0.955598,1.076266,1.008217,...,1.081320,0.926907,1.011084,1.015210,1.058710,0.985643,1.012339,0.944092,1.022843,0.963133
2024-05-31,1.001899,1.008152,1.001000,0.977051,0.978943,0.986191,0.981269,0.971669,1.016751,1.034494,...,0.929420,1.019506,0.988135,0.938288,1.014242,1.003520,1.033162,0.936449,0.991827,0.996972

In [ ]:
df_mret_11 = df_mret.rolling(11).apply(np.prod).dropna()
df_mret_11

Ticker,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BHARTIARTL.NS,BPCL.NS,...,SHRIRAMFIN.NS,SUNPHARMA.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,ULTRACEMCO.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2014-11-30,1.707721,1.857006,1.202982,1.490145,1.861941,1.377282,1.513748,1.968955,1.131902,2.137027,...,1.606516,1.467109,1.004984,1.422856,1.111411,1.227418,1.444150,1.606802,1.404126,1.059888
2014-12-31,2.036006,2.171147,1.214470,1.594870,2.236965,1.279227,1.922591,2.275381,1.119683,1.781086,...,1.772713,1.404026,1.070567,1.417680,1.121753,1.141541,1.451384,1.722636,1.564301,0.965481
2015-01-31,2.467257,2.039163,1.427306,1.813425,2.320745,1.228813,2.004639,2.577506,1.299374,1.981085,...,1.932093,1.423530,1.136006,1.403406,1.135689,1.090651,1.536216,1.775670,1.707454,1.015571
2015-02-28,1.933016,1.847159,1.420863,1.473036,1.941630,1.032108,1.804644,2.293188,1.117860,1.617759,...,1.507883,1.529187,1.039987,1.442744,0.890088,1.248084,1.579497,1.657213,1.429297,1.204529
2015-03-31,1.472658,1.637620,1.530944,1.606058,1.846164,1.054624,1.699874,2.197150,1.198903,1.782370,...,1.516535,1.618047,0.995651,1.326582,0.790590,1.166613,1.374778,1.536590,1.419678,1.203886
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-31,2.303772,2.038400,1.443311,1.045620,1.264957,2.094272,1.219043,1.122838,1.577231,1.582953,...,2.049944,1.482804,1.562981,2.101735,1.307840,1.151863,1.212134,1.558307,1.400211,1.235370
2024-02-29,1.876889,2.089729,1.415389,1.021817,1.252300,2.036000,1.258429,1.156425,1.499800,1.753848,...,1.936319,1.605076,1.678846,2.258080,1.347847,1.277364,1.156101,1.441171,1.297849,1.419849
2024-03-31,1.660874,1.969544,1.408335,0.980843,1.217674,2.064137,1.213487,1.153684,1.537095,1.684564,...,1.770824,1.640814,1.435098,2.047221,1.443724,1.204100,1.219205,1.439067,1.290219,1.247013
2024-04-30,1.225139,1.793192,1.286708,0.900703,1.274417,1.949498,1.112987,0.990515,1.555830,1.670839,...,1.822968,1.540063,1.387779,1.915068,1.559546,1.161468,1.132625,1.271319,1.267063,1.145547
2024-05-31,1.281590,1.806831,1.167677,0.835770,1.155856,1.871599,1.037140,0.939502,1.529957,1.722786,...,1.366759,1.456257,1.272157,1.587944,1.494196,1.161057,1.154353,1.102866,1.192363,1.184633

In [ ]:
top_10 = df_mret_11.loc['2014-11-30'].nlargest(10)
top_10

Ticker
EICHERMOT.NS     2.902608
BPCL.NS          2.137027
BAJFINANCE.NS    1.968955
MARUTI.NS        1.896939
AXISBANK.NS      1.861941
ADANIPORTS.NS    1.857006
SBIN.NS          1.820912
BRITANNIA.NS     1.794273
INDUSINDBK.NS    1.772647
ADANIENT.NS      1.707721
Name: 2014-11-30 00:00:00, dtype: float64

In [ ]:
top_10.name

Timestamp('2014-11-30 00:00:00')

In [ ]:
df_mret[top_10.name:][1:2]

Ticker,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BHARTIARTL.NS,BPCL.NS,...,SHRIRAMFIN.NS,SUNPHARMA.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,ULTRACEMCO.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2014-12-31,1.059593,1.099225,0.968826,1.010205,1.044056,0.921103,1.136494,1.126817,0.922574,0.865662,...,1.026299,0.98434,0.935834,0.928866,0.843773,0.967934,0.982387,1.029122,1.077206,0.947764

In [ ]:
# df_mret['2014-11-30':][1:2][top_10.index]
df_mret[top_10.name:][1:2][top_10.index]

Ticker,EICHERMOT.NS,BPCL.NS,BAJFINANCE.NS,MARUTI.NS,AXISBANK.NS,ADANIPORTS.NS,SBIN.NS,BRITANNIA.NS,INDUSINDBK.NS,ADANIENT.NS
Date,,,,,,,,,,
2014-12-31,1.038316,0.865662,1.126817,0.995099,1.044056,1.099225,0.970286,1.116599,1.069292,1.059593

In [ ]:
#return of portfolio
df_mret['2014-11-30':][1:2][top_10.index].mean(axis=1)
# df_mret[1:2][top_10.index].mean(axis=1)

Date
2014-12-31    1.038495
Freq: M, dtype: float64

In [ ]:
def top_performers(date):
  top = df_mret_11.loc[date].nlargest(10)
  port_mret = df_mret[date:][1:2][top.index].mean(axis=1).values[0]
  return port_mret

In [ ]:
top_performers('2014-11-30')

1.0384945155125986

In [ ]:
monthly_ret = []
i = 0
for date in df_mret_11.index[:-1]:
  monthly_ret.append(top_performers(date))
  i = i+1
  print('month',i,'th return : ',monthly_ret[i-1])

month 1 th return :  1.0384945155125986
month 2 th return :  1.1014970969050302
month 3 th return :  1.013649793212834
month 4 th return :  0.9894621659167913
month 5 th return :  0.9789243276245756
month 6 th return :  1.07180322958649
month 7 th return :  0.982643844247581
month 8 th return :  1.0764862062903802
month 9 th return :  0.9521687217209192
month 10 th return :  1.0086391253589173
month 11 th return :  0.9932012219943772
month 12 th return :  0.9662810330372148
month 13 th return :  1.0343424845834328
month 14 th return :  0.9637589051969291
month 15 th return :  0.9215817096617591
month 16 th return :  1.0504820743243595
month 17 th return :  1.019278846136167
month 18 th return :  1.0490726780114519
month 19 th return :  1.047299776660409
month 20 th return :  1.1057553735137404
month 21 th return :  1.0473896288330657
month 22 th return :  0.984229034203507
month 23 th return :  1.0122297480314673
month 24 th return :  0.9736194262435246
month 25 th return :  0.9497043074921823
month 26 th return :  1.1365186864890187
month 27 th return :  1.0052630626187642
month 28 th return :  1.0356592898275516
month 29 th return :  1.0321606944930761
month 30 th return :  1.013697370322612
month 31 th return :  0.9972798671380255
month 32 th return :  1.0977875136149773
month 33 th return :  1.032723994564065
month 34 th return :  0.9690137074234585
month 35 th return :  1.0795896971017707
month 36 th return :  1.0553265205736635
month 37 th return :  1.0400803301509365
month 38 th return :  1.024358612116983
month 39 th return :  0.9865597834322053
month 40 th return :  0.955017278448401
month 41 th return :  1.102271125301958
month 42 th return :  0.9920825908495597
month 43 th return :  1.0050061490450262
month 44 th return :  1.0463546893110767
month 45 th return :  1.0735662130115535
month 46 th return :  0.9444201071679789
month 47 th return :  0.9968602867639748
month 48 th return :  0.9899128265942654
month 49 th return :  1.0174464288838307
month 50 th return :  0.992427680601519
month 51 th return :  0.9935254613118312
month 52 th return :  1.0241072904538837
month 53 th return :  1.0145311643169141
month 54 th return :  1.006554949281966
month 55 th return :  1.013660567665769
month 56 th return :  0.9051302255710656
month 57 th return :  1.018822066988395
month 58 th return :  1.078083100534859
month 59 th return :  1.0410046529048822
month 60 th return :  0.9891327490357973
month 61 th return :  1.0149962526891523
month 62 th return :  1.0319959260492193
month 63 th return :  0.9714320461988185
month 64 th return :  0.7604005939286909
month 65 th return :  1.1199892837855934
month 66 th return :  1.00881611348608
month 67 th return :  1.0188611785331836
month 68 th return :  1.0998978427538353
month 69 th return :  1.0244315921363092
month 70 th return :  1.0339726295513836
month 71 th return :  1.0219240450065112
month 72 th return :  1.0634505627665682
month 73 th return :  1.110905844801892
month 74 th return :  0.9761222596975058
month 75 th return :  1.079861994920917
month 76 th return :  1.0532142409434462
month 77 th return :  1.0988485289251715
month 78 th return :  1.0679199345065933
month 79 th return :  1.0228418221442805
month 80 th return :  1.062310193519817
month 81 th return :  1.0575050878041234
month 82 th return :  0.9795012687283101
month 83 th return :  1.0523206805020655
month 84 th return :  0.9559824045973109
month 85 th return :  1.027772518202479
month 86 th return :  0.950276836604861
month 87 th return :  0.995205823157115
month 88 th return :  1.0381458010942535
month 89 th return :  0.9427058969279267
month 90 th return :  0.9519631240490696
month 91 th return :  0.9650802587858907
month 92 th return :  1.046310746304532
month 93 th return :  1.0877547526369937
month 94 th return :  0.9811945329566907
month 95 th return :  1.0575210358352676
month 96 th return :  0.9924650591131623
month 97 th return :  0.98343959538423
month 98 th return :  0.9736611184524449
month 99 th return :  0.9262653973891277
month 100 th return :  0.9951477829865805
month 101 th return :  1.0452978561154576
month 102 th return :  1.021681390324226
month 103 th return :  1.050890027379809
month 104 th return :  1.024209372959349
month 105 th return :  0.9766478438316117
month 106 th return :  1.0543181068310399
month 107 th return :  0.9780416313157987
month 108 th return :  1.071136664791504
month 109 th return :  1.0857253482991316
month 110 th return :  1.08806616450063
month 111 th return :  1.0372182316394796
month 112 th return :  1.0230539660690603
month 113 th return :  1.0166232830470263
month 114 th return :  1.0076408858342756

In [ ]:
# total return of our portfolio in last 10 years
pd.Series(monthly_ret).prod()

6.995240771091297

In [ ]:
# COMBINED CODE

import yfinance as yf
import numpy as np
import pandas as pd

stocks = pd.read_html('https://en.wikipedia.org/wiki/NIFTY_50')[2].Symbol
stocks = stocks + '.NS'

df = yf.download(stocks.to_list(), start = '2014-01-01')
print(df.head())
df_dret = df_close.pct_change()
df_mret = (df_dret +1).resample('M').prod()
df_mret_11 = df_mret.rolling(11).apply(np.prod).dropna()

def top_performers(date):
  top = df_mret_11.loc[date].nlargest(10)
  port_mret = df_mret[date:][1:2][top.index].mean(axis=1).values[0]
  return port_mret

monthly_ret = []
i = 0
for date in df_mret_11.index[:-1]:
  monthly_ret.append(top_performers(date))
  i = i+1
  print('month',i,'th return : ',monthly_ret[i-1])

# total return of our portfolio in last 10 years
print("\nPortfolio's total return for last ",i,"months is ",
      pd.Series(monthly_ret).prod())

[*********************100%%**********************]  50 of 50 completed

Price        Adj Close                                                        \
Ticker     ADANIENT.NS ADANIPORTS.NS APOLLOHOSP.NS ASIANPAINT.NS AXISBANK.NS
Date
2014-01-01   37.967480    148.394302    932.331421    464.536194  248.000092
2014-01-02   36.074406    144.928940    895.059448    451.336792  244.180862
2014-01-03   35.085476    142.318008    915.643188    455.008484  241.992966
2014-01-06   35.608196    143.219971    909.631592    456.077484  241.110123
2014-01-07   34.181328    138.567780    896.550171    455.426819  236.878265

Price                                                                          \
Ticker     BAJAJ-AUTO.NS BAJAJFINSV.NS BAJFINANCE.NS BHARTIARTL.NS    BPCL.NS
Date
2014-01-01   1459.791138     75.509598    152.003906    288.068939  69.372292
2014-01-02   1446.582153     72.355507    151.897430    280.350159  67.435349
2014-01-03   1443.156006     72.449883    150.571274    280.904510  65.418938
2014-01-06   1437.636353     72.688301    150.179245    280.904510  65.518280
2014-01-07   1438.892456     72.623734    150.430939    282.908875  64.276634

Price       ...        Volume                                           \
Ticker      ... SHRIRAMFIN.NS SUNPHARMA.NS TATACONSUM.NS TATAMOTORS.NS
Date        ...
2014-01-01  ...       52540.0       425464       1958707       1364747
2014-01-02  ...      104861.0      1311399       2116255       3015089
2014-01-03  ...      166850.0      1443488       1816178       5004049
2014-01-06  ...      223531.0      1832494       1538685       5490077
2014-01-07  ...      322912.0      2986634       1244854       4020899

Price
Ticker     TATASTEEL.NS   TCS.NS TECHM.NS TITAN.NS ULTRACEMCO.NS WIPRO.NS
Date
2014-01-01     12526105   529952   698232   538938         51796  1181351
2014-01-02     41987111  1726948  1395500  1570396         81220  2441295
2014-01-03     33417104  2618174  1327296   818984         78848  2953767
2014-01-06     28387844  2311810  1485056   497192         65748  4948206
2014-01-07     40939015  2897486  1914320   713955         98004  3286111

[5 rows x 300 columns]
month 1 th return :  1.0384945155125986
month 2 th return :  1.1014970969050302
month 3 th return :  1.013649793212834
month 4 th return :  0.9894621659167913
month 5 th return :  0.9789243276245756
month 6 th return :  1.07180322958649
month 7 th return :  0.982643844247581
month 8 th return :  1.0764862062903802
month 9 th return :  0.9521687217209192
month 10 th return :  1.0086391253589173
month 11 th return :  0.9932012219943772
month 12 th return :  0.9662810330372148
month 13 th return :  1.0343424845834328
month 14 th return :  0.9637589051969291
month 15 th return :  0.9215817096617591
month 16 th return :  1.0504820743243595
month 17 th return :  1.019278846136167
month 18 th return :  1.0490726780114519
month 19 th return :  1.047299776660409
month 20 th return :  1.1057553735137404
month 21 th return :  1.0473896288330657
month 22 th return :  0.984229034203507
month 23 th return :  1.0122297480314673
month 24 th return :  0.9736194262435246
month 25 th return :  0.9497043074921823
month 26 th return :  1.1365186864890187
month 27 th return :  1.0052630626187642
month 28 th return :  1.0356592898275516
month 29 th return :  1.0321606944930761
month 30 th return :  1.013697370322612
month 31 th return :  0.9972798671380255
month 32 th return :  1.0977875136149773
month 33 th return :  1.032723994564065
month 34 th return :  0.9690137074234585
month 35 th return :  1.0795896971017707
month 36 th return :  1.0553265205736635
month 37 th return :  1.0400803301509365
month 38 th return :  1.024358612116983
month 39 th return :  0.9865597834322053
month 40 th return :  0.955017278448401
month 41 th return :  1.102271125301958
month 42 th return :  0.9920825908495597
month 43 th return :  1.0050061490450262
month 44 th return :  1.0463546893110767
month 45 th return :  1.0735662130115535
month 46 th return :  0.9444201071679789
month 47 th return :  0.9968602867639748
month 48 th return :  0.9899128265942654
month 49 th return :  1.0174464288838307
month 50 th return :  0.992427680601519
month 51 th return :  0.9935254613118312
month 52 th return :  1.0241072904538837
month 53 th return :  1.0145311643169141
month 54 th return :  1.006554949281966
month 55 th return :  1.013660567665769
month 56 th return :  0.9051302255710656
month 57 th return :  1.018822066988395
month 58 th return :  1.078083100534859
month 59 th return :  1.0410046529048822
month 60 th return :  0.9891327490357973
month 61 th return :  1.0149962526891523
month 62 th return :  1.0319959260492193
month 63 th return :  0.9714320461988185
month 64 th return :  0.7604005939286909
month 65 th return :  1.1199892837855934
month 66 th return :  1.00881611348608
month 67 th return :  1.0188611785331836
month 68 th return :  1.0998978427538353
month 69 th return :  1.0244315921363092
month 70 th return :  1.0339726295513836
month 71 th return :  1.0219240450065112
month 72 th return :  1.0634505627665682
month 73 th return :  1.110905844801892
month 74 th return :  0.9761222596975058
month 75 th return :  1.079861994920917
month 76 th return :  1.0532142409434462
month 77 th return :  1.0988485289251715
month 78 th return :  1.0679199345065933
month 79 th return :  1.0228418221442805
month 80 th return :  1.062310193519817
month 81 th return :  1.0575050878041234
month 82 th return :  0.9795012687283101
month 83 th return :  1.0523206805020655
month 84 th return :  0.9559824045973109
month 85 th return :  1.027772518202479
month 86 th return :  0.950276836604861
month 87 th return :  0.995205823157115
month 88 th return :  1.0381458010942535
month 89 th return :  0.9427058969279267
month 90 th return :  0.9519631240490696
month 91 th return :  0.9650802587858907
month 92 th return :  1.046310746304532
month 93 th return :  1.0877547526369937
month 94 th return :  0.9811945329566907
month 95 th return :  1.0575210358352676
month 96 th return :  0.9924650591131623
month 97 th return :  0.98343959538423
month 98 th return :  0.9736611184524449
month 99 th return :  0.9262653973891277
month 100 th return :  0.9951477829865805
month 101 th return :  1.0452978561154576
month 102 th return :  1.021681390324226
month 103 th return :  1.050890027379809
month 104 th return :  1.024209372959349
month 105 th return :  0.9766478438316117
month 106 th return :  1.0543181068310399
month 107 th return :  0.9780416313157987
month 108 th return :  1.071136664791504
month 109 th return :  1.0857253482991316
month 110 th return :  1.08806616450063
month 111 th return :  1.0372182316394796
month 112 th return :  1.0230539660690603
month 113 th return :  1.0166232830470263
month 114 th return :  1.0076408858342756

Portfolio's total return for last  114 months is  6.995240771091297